### ISSUE TITLE
Difference between dataset_low_res.zips in MVSNet page and BlendedMVS page

### ISSUE THREAD

**Issue by MiZhenxing** [YoYo000/BlendedMVS#16]
Hi, YaoYao,

Thank you for your excellent work on 3D datasets! 
I found in [MVSNet](https://github.com/YoYo000/MVSNet) that you provide a link of Preprocessed training/validation data: [BlendedMVS](https://drive.google.com/open?id=1ilxls-VJNvJnB7IaFj7P0ehMPr7ikRCb), which is about 23G. Also in [BlendedMVS page](https://github.com/YoYo000/BlendedMVS) you provide another link of [low-res set (27.5 GB) ](https://1drv.ms/u/s!Ag8Dbz2Aqc81gVDgxb8MDGgoV74S?e=hJKlvV). So I would ask what are the differences between the two versions and which one is better to use. 

Thank you!

**Comment by YoYo000** [comment]
Hi @MiZhenxing, the two sets of inputs are almost the same, except that dataset in the BlendedMVS page has fixed a bug on multi-texture mesh rendering. 

I would suggest you use the one on the BlendedMVS page.


<img width="686" alt="Screenshot 2021-03-21 at 6 08 09 PM" src="https://user-images.githubusercontent.com/17586209/111900979-66c3a480-8a70-11eb-8a77-86701eab461c.png">

**Comment by MiZhenxing** [comment]
Thanks for your helpful response and suggenstion!
