### ISSUE TITLE
Question about training / validation split

### ISSUE THREAD

**Issue by morsingher** [YoYo000/BlendedMVS#19]
Hi, thank you for the amazing data! I was wondering why the training / validation split is so uneven (106 / 7). Is there a particular reason or any reasonable 80% / 20% split chosen at random would work, as for most other datasets?

**Comment by YoYo000** [comment]
Hi @morsingher , there is no particular reason for choosing the 7 validation scenes. I randomly select 7 scenes for MVS evaluations. If needed, you could apply more scenes for your own tasks.
