### ISSUE TITLE
How to get the high-resolution set?

### ISSUE THREAD

**Issue by FishHe** [YoYo000/BlendedMVS#2]
I'd like to test a new deep model with the high-resolution set.
Would it be possible to share?
Here's my email address: zhangdengsu@whu.edu.cn

**Comment by KevinCain** [comment]
I'd also appreciate access to the high-resolution set, for a cascade cost volume implementation favoring larger images. My contact email is:
Kevin Cain: kevin@insightdigital.org

**Comment by YoYo000** [comment]
> I'd also appreciate access to the high-resolution set, for a cascade cost volume implementation favoring larger images. My contact email is:
> Kevin Cain: [kevin@insightdigital.org](mailto:kevin@insightdigital.org)

Sent :)

**Comment by chaytonmin** [comment]
I'd  appreciate it if you could send me the the high-resolution set. 
My email address: chaytonmin@qq.com.
Thanks a lot!

**Comment by KevinCain** [comment]
> > I'd also appreciate access to the high-resolution set, for a cascade cost volume implementation favoring larger images. My contact email is:
> > Kevin Cain: [kevin@insightdigital.org](mailto:kevin@insightdigital.org)
> 
> Sent :)

Thanks @YoYo000 for very kindly sharing -- I don't seem to have an email from you, could you please resend to kevin@insightdigital.org? Sorry!

**Comment by chaytonmin** [comment]
> I'd like to test a new deep model with the high-resolution set.
> Would it be possible to share?
> Here's my email address: [zhangdengsu@whu.edu.cn](mailto:zhangdengsu@whu.edu.cn)

Have you got the high-resolution dataset？

**Comment by AbegNext** [comment]
hi @YoYo000, I would appreciate it if you could send me the high-resolution dataset to ing.a.lama@gmail.com. I would like to try it on a couple of networks. Thanks.

**Comment by saulzar** [comment]
I'm also keen to experiment on the high-resolution set.

Thanks,
oliver.batchelor@canterbury.ac.nz

**Comment by kwea123** [comment]
@YoYo000 Hi, I also want to experiment the high resolution set.

**Comment by leejaeyong7** [comment]
Hi!

Would you also send me the high res dataset to leejaeyong7@gmail.com please?
Thanks!

**Comment by Txusheng** [comment]
@YoYo000 
Hi!
Your  BlendedMVS dataset is really a great contribution the the learned MVS research!
We desperately want the high-res dataset! Can you please also share your high-res dataset with me? My email address is tiancai70@gmail.com
Thank you very much!

**Comment by VILmchen** [comment]
Hi!
I'd like to test a model with the high-resolution set.
Could you also send me the high res dataset to 747135680@qq.com?
Thanks a lot!
