### ISSUE TITLE
How to change ply results of MVSNet to obj ？

### ISSUE THREAD

**Issue by chaytonmin** [YoYo000/BlendedMVS#3]
I find that the dataset on the website Altizure is great. How can I to change ply results of MVSNet to obj and the results of mvsnet can be the same as shown in Altizure?

**Comment by YoYo000** [comment]
Basically you cannot. MVSNet is a multi-view stereo algorithm, which is only a small part contributes to the whole 3D reconstruction pipeline.

**Comment by chaytonmin** [comment]
> Basically you cannot. MVSNet is a multi-view stereo algorithm, which is only a small part contributes to the whole 3D reconstruction pipeline.

Thanks a lot!

I have another question. what is the meaning of the last line in cams of the new blendedMVS dataset?
 
![捕获](https://user-images.githubusercontent.com/40260488/74901227-172e2780-53dd-11ea-8b55-e1da1642ea64.PNG)

**Comment by kwea123** [comment]
from the MVSNet repo, it seems it's
```
DEPTH_MIN DEPTH_INTERVAL DEPTH_NUM DEPTH_MAX 
```

**Comment by chaytonmin** [comment]
How to get the final textured mesh in supplementaries？
I downloaded the textured mesh in  supplementaries. However, they are divided into many small parts？ How to merge them ？

**Comment by YoYo000** [comment]
You can drag all mesh files together into meshlab to view the model. Some of the scenes are too large so we can only store them in different files.

**Comment by chaytonmin** [comment]
> You can drag all mesh files together into meshlab to view the model. Some of the scenes are too large so we can only store them in different files.

Thanks！
