### ISSUE TITLE
Onedrive broke down

### ISSUE THREAD

**Issue by Rlee719** [YoYo000/BlendedMVS#33]
Hi, I was trying to download the textured mesh from the provided link, https://1drv.ms/u/s!Ag8Dbz2Aqc81fkvi2X9Mmzan0FI?e=7x2WoS

However it does not work. Any ideas?

**Comment by pietertolsma** [comment]
Having the same problem

**Comment by JQJ001** [comment]
Having the same problem.
Hello, did you successfully download the textured meshes? @Rlee719
