### ISSUE TITLE
What is the detailed context of BlendedMVG_list.txt?

### ISSUE THREAD

**Issue by ritatsaoo** [YoYo000/BlendedMVS#6]
Thanks a lot for this released dataset. I am wondering the detailed context or format of BlendedMVG_list.txt. Looking forward the reply and appreciating the kind assistance.

**Comment by YoYo000** [comment]
Each line in BlendedMVG_list.txt is a PID that represents a scene. You can download the dataset and find all scenes in the .zip file.
