### ISSUE TITLE
Unit of the ground truth depth.

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [YoYo000/BlendedMVS#7]
First of all, thank you for publishing this promising dataset.

I have a question about the unit of the given ground truth depth map.

![depth](https://user-images.githubusercontent.com/32631453/83105616-f4a35d00-a0f5-11ea-9870-dd3fb797c515.png)

As in the figure above, I include the two depth maps that correspond to two upper rgb images.
Typically, I include the colorbar to check the range of depth, but I found the range looks weird.

Do I have to divide depth maps into 256 as the KITTI dataset? 
I used to the same code in (MVSNet) but still cannot solve this problem.

As far as my understanding, the DTU dataset provides gt depth maps in the millimeter unit. 
I have no idea about this set.

Sincerely.

**Comment by YoYo000** [comment]
The units of the scene may not be defined. 

If the input images contain GPS information, we will align the SfM coordinate system to the GPS coordinate, in this case, the unit should be meter. Otherwise, the SfM system is up-to-scale and the unit is not defined.

**Comment by LifeBeyondExpectations** [comment]
Thank you for your answer. I will close this question.
