### ISSUE TITLE
Info about datasets

### ISSUE THREAD

**Issue by phongnhhn92** [YoYo000/BlendedMVS#9]
Hi, 
I would like to ask what is the difference between 3 version of BlendMVS. I see that the normal BlendMVS is the smallest set but I am confused to see that BlendMVS++ is smaller than BlendMVS+. I would like to know the difference to write my paper.

**Comment by YoYo000** [comment]
The BlendedMVS+ and BlendedMVS++ are two additional sets to BlendedMVS. If you want to use the whole BlendedMVG dataset (502 scenes), then you need to use all three sets (BlendedMVS & BlendedMVS+ & BlendedMVS++)

**Comment by phongnhhn92** [comment]
Thanks for your clarification !
